<parameters>
	<requestType>update</requestType>
	<table>pages</table>
	<fields>
		<field>
			<name>
				url
			</name>
			<value>
				another test
			</value>
		</field>
	</fields>
	<resourceList>
		<resource>
			<id>10</id>
		</resource>
	</resourceList>
</parameters>