hello.lo: /home/kevin/public_html/CoagmentoMiddleLayer/application/extension/text_processing/hello.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/kevin/public_html/CoagmentoMiddleLayer/application/extension/text_processing $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/kevin/public_html/CoagmentoMiddleLayer/application/extension/text_processing/hello.c -o hello.lo 
$(phplibdir)/text_processing.la: ./text_processing.la
	$(LIBTOOL) --mode=install cp ./text_processing.la $(phplibdir)

./text_processing.la: $(shared_objects_text_processing) $(TEXT_PROCESSING_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_text_processing) $(TEXT_PROCESSING_SHARED_LIBADD)

